FROM python:3.7.17

WORKDIR /app

COPY . /app

RUN pip install -r requirements.txt && pip install fastapi uvicorn

EXPOSE 80

CMD ["uvicorn", "speech_endpoint:app", "--host", "0.0.0.0", "--port", "80"]